### ISSUE TITLE
Missing dll file

### ISSUE THREAD

**Issue by MP3Martin** [Owen013/FirstPersonPresence#1]
This is an underrated mod. It makes walking while holding an item/tool look way better. But there is one issue with [v1.2.1](https://github.com/Owen013/FirstPersonPresence/releases/tag/v1.2.1). I think you have accidentally included the `.pdb` file instead of the `.dll` file. Other versions are not affected. The problem is only with the release asset, not with the code.

**Comment by Owen013** [comment]
I just edited the release to include the correct files. Try reinstalling to make sure it worked. I'm so sorry about that!

Also, thank you!
